### ISSUE TITLE
register games

### ISSUE THREAD

**Issue by emgrasmeder** [emgrasmeder/pingpong#1]
user should be able to 
- [x] select Games tab (#2)
- [x] Add Game details (#3)
  1. select "create new game" 
  3. add player as "home team"
  4. add player as "away team"
  5. select date 
  6. save
  7. new game is registered in db 
  8. it's displayed correctly on the list
  9. (delete / edit possible)
- [ ] home/away players are searchable in player db (#4)
